const SEVERITY = {
  high:   'bg-red-100 text-red-700 border-red-200',
  medium: 'bg-amber-100 text-amber-700 border-amber-200',
  low:    'bg-slate-100 text-slate-600 border-slate-200',
}

function StatCard({ label, value, sub, accent }) {
  return (
    <div className={`rounded-xl p-5 border ${accent
      ? 'bg-emerald-600 border-emerald-600 text-white'
      : 'bg-white border-slate-200'}`}
    >
      <p className={`text-xs font-semibold uppercase tracking-wider mb-1 ${accent ? 'text-emerald-100' : 'text-slate-400'}`}>
        {label}
      </p>
      <p className={`text-2xl font-bold ${accent ? 'text-white' : 'text-slate-900'}`}>{value}</p>
      {sub && <p className={`text-xs mt-1 ${accent ? 'text-emerald-100' : 'text-slate-400'}`}>{sub}</p>}
    </div>
  )
}

function Section({ title, children }) {
  return (
    <div>
      <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-3">{title}</h3>
      {children}
    </div>
  )
}

function Prose({ text }) {
  return <p className="text-sm text-slate-700 leading-relaxed">{text}</p>
}

function pct(v)  { return `${(v * 100).toFixed(1)}%` }
function usd(v)  { return `$${v.toFixed(1)}M` }
function yrs(v)  { return `${v.toFixed(1)} yrs` }
function delta(v){ return v >= 0 ? `+${pct(v)}` : pct(v) }

export default function MemoCard({ memo, onReset }) {
  const irr_delta = memo.irr_with_credits - memo.irr_without_credits

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      {/* Title */}
      <div className="flex items-start justify-between">
        <div>
          <h2 className="text-2xl font-bold text-slate-900">{memo.project_name}</h2>
          <p className="text-slate-500 text-sm mt-0.5">
            {memo.capacity_mw} MW {memo.technology} · {memo.county} County, {memo.state}
          </p>
        </div>
        <span className="px-3 py-1 bg-emerald-100 text-emerald-700 text-xs font-semibold rounded-full border border-emerald-200">
          {memo.recommended_credit}
        </span>
      </div>

      {/* Disclaimer banner */}
      <div className="flex items-start gap-3 bg-amber-50 border border-amber-200 rounded-lg px-4 py-3">
        <span className="text-amber-500 text-base leading-none mt-0.5">⚠</span>
        <p className="text-xs text-amber-800 leading-relaxed">
          <span className="font-semibold">For informational purposes only.</span> This output is
          generated by an AI system and does not constitute legal, tax, or financial advice.
          Consult qualified tax counsel before making investment decisions. The developers of
          Basis accept no liability for losses arising from reliance on this analysis.
        </p>
      </div>

      {/* Stat row */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <StatCard label="Credit value"   value={usd(memo.credit_value_millions)} sub={`${pct(memo.stacked_rate)} stacked rate`} accent />
        <StatCard label="IRR w/ credits" value={pct(memo.irr_with_credits)}      sub={`${delta(irr_delta)} vs no credit`} />
        <StatCard label="NPV"            value={usd(memo.npv_with_credits)}       sub="with IRA credits" />
        <StatCard label="Payback"        value={yrs(memo.payback_years)}          sub="with IRA credits" />
      </div>

      {/* Executive summary */}
      <div className="bg-white rounded-xl border border-slate-200 p-6 shadow-sm">
        <Section title="Executive summary">
          <Prose text={memo.executive_summary} />
        </Section>
      </div>

      {/* Analysis grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div className="bg-white rounded-xl border border-slate-200 p-6 shadow-sm">
          <Section title="Credit analysis">
            <Prose text={memo.credit_analysis} />
          </Section>
        </div>
        <div className="bg-white rounded-xl border border-slate-200 p-6 shadow-sm">
          <Section title="Financial analysis">
            <Prose text={memo.financial_analysis} />
          </Section>
        </div>
      </div>

      {/* IRR comparison */}
      <div className="bg-white rounded-xl border border-slate-200 p-6 shadow-sm">
        <Section title="IRR impact of IRA credits">
          <div className="flex items-center gap-6 mt-2">
            <div>
              <p className="text-xs text-slate-400 mb-0.5">Without credits</p>
              <p className="text-lg font-bold text-slate-500">{pct(memo.irr_without_credits)}</p>
            </div>
            <div className="flex-1 flex items-center gap-2">
              <div className="h-px flex-1 bg-slate-200" />
              <span className="text-xs text-emerald-600 font-semibold bg-emerald-50 border border-emerald-200 px-2 py-0.5 rounded-full">
                {delta(irr_delta)}
              </span>
              <div className="h-px flex-1 bg-slate-200" />
            </div>
            <div className="text-right">
              <p className="text-xs text-slate-400 mb-0.5">With credits</p>
              <p className="text-lg font-bold text-emerald-600">{pct(memo.irr_with_credits)}</p>
            </div>
          </div>
        </Section>
      </div>

      {/* Risk flags */}
      {memo.risk_flags?.length > 0 && (
        <div className="bg-white rounded-xl border border-slate-200 p-6 shadow-sm">
          <Section title="Risk flags">
            <div className="space-y-2 mt-1">
              {memo.risk_flags.map((flag, i) => (
                <div key={i} className={`flex items-start gap-3 p-3 rounded-lg border ${SEVERITY[flag.severity] ?? SEVERITY.low}`}>
                  <span className="text-xs font-bold uppercase tracking-wider mt-0.5 w-12 flex-shrink-0">
                    {flag.severity}
                  </span>
                  <div>
                    <p className="text-sm font-semibold">{flag.flag}</p>
                    <p className="text-xs mt-0.5 opacity-80">{flag.detail}</p>
                  </div>
                </div>
              ))}
            </div>
          </Section>
        </div>
      )}

      {/* Regulatory note */}
      {memo.regulatory_note && (
        <div className="bg-amber-50 border border-amber-200 rounded-xl p-5">
          <p className="text-xs font-semibold text-amber-700 uppercase tracking-wider mb-1">
            Regulatory context
          </p>
          <p className="text-sm text-amber-800">{memo.regulatory_note}</p>
        </div>
      )}

      {/* Recommendation */}
      <div className="bg-slate-900 rounded-xl p-6 text-white">
        <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">
          Recommendation
        </p>
        <p className="text-sm leading-relaxed">{memo.recommendation}</p>
      </div>

      {/* Footer */}
      <div className="text-center pb-6">
        <button
          onClick={onReset}
          className="text-sm text-slate-400 hover:text-slate-600 transition-colors"
        >
          ← Run another analysis
        </button>
      </div>
    </div>
  )
}
